# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TKhX-hOiK7q8LuPhh5AmWacKqc3bEHGG
"""

from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer

df = pd.read_csv('1.csv')


df.head(10)
df.describe()

imputer = SimpleImputer(strategy='constant')
df2 = pd.DataFrame(imputer.fit_transform(df),columns=df.columns)

#for i in df2.deaths:
#  print(i)
df2.columns

#countries = df2['deaths'].unique()
#len(countries)

#for idx in range(0,len(df2)):
#  print(idx)


plt.scatter(str(df2.deaths), str(df2.tests), color='red',label='Deaths')
plt.scatter(str(df2.tests), str(df2.vaccines), color='blue',label='Tests')
plt.scatter(str(df2.vaccines), str(df2.deaths), color='green',label='Vaccines')
plt.legend()
plt.show()

"""# Yeni Bölüm"""

